#DO NOT TOUCH!
test: true


#Format, supports placeholderapi, replaces [Faction] with your faction if you are using savagefactions or factionsuuid.

#variables:
#[Faction]
#[chatcolor]
#[username]
format: "[Faction]&r %vault_prefix% &7%player_name%&7: &r"

color:
  Wqrld: "dsa"