#Format, supports placeholderapi, replaces [Faction] with your faction if you are using savagefactions or factionsuuid.

#variables:
#[faction]
#[chatcolor]
#[username]
#[prefix]

#Any PlaceholderAPI veriable for example %player_name%

format: "[faction]&r[prefix]&r &7[username]&7: &r[chatcolor][message]"

#Colors for [chatcolor]
color:
  owner: "&b"

#Default chatcolor used in [chatcolor]
defaultcolor: "&f"